# Generated by Django 4.2.7 on 2023-12-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("L", "Low Priority"),
                    ("M", "Medium Priority"),
                    ("H", "High Priority"),
                ],
                default="L",
                max_length=100,
            ),
        ),
    ]
