# Generated by Django 4.2.7 on 2023-12-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0003_alter_task_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="time_completed",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("L", "Low"), ("M", "Medium"), ("H", "High")],
                default="L",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("IP", "In progress"),
                    ("IPAD", "In progress after the deadline"),
                    ("COT", "Completed on time"),
                    ("CAD", "Completed after the deadline"),
                ],
                default="IP",
                max_length=100,
            ),
        ),
    ]
