# Generated by Django 4.2.7 on 2023-12-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0004_task_time_completed_alter_task_priority_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("L", "Low"), ("M", "Medium"), ("H", "High")],
                default="L",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("IP", "In progress"),
                    ("IPAD", "In progress after the deadline"),
                    ("COT", "Completed on time"),
                    ("CAD", "Completed after the deadline"),
                ],
                default="IP",
                max_length=50,
            ),
        ),
    ]
